### Test server
GET http://localhost:8080

### Test database
GET http://localhost:8080/test-db

### Signup
POST http://localhost:8080/auth/signup
Content-Type: application/json

{
  "username": "testuser",
  "email": "test@gmail.com",
  "password": "test123",
  "country": "USA",
  "role": "user",
  "user_type": "caregiver"
}

### Login
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "email": "test@gmail.com",
  "password": "test123"
}

### Get all posts
GET http://localhost:8080/posts

###Get single post
GET http://localhost:8080/posts/1

### Create post
POST http://localhost:8080/posts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Miwicm9sZSI6InVzZXIiLCJpYXQiOjE3NzU3MDk5MjgsImV4cCI6MTc3NjMxNDcyOH0.xYDaFyXAtSuTd_mI24wtp3oYYzpuHC4lYw5qmiPAkAw

{
  "description": "testing testing check 1 2",
  "image_url": "https://embeddings/image.jpg",
  "country_origin": "US",
  "category": "mobility",
  "disability_type": "CP",
  "post_type": "discovery"
}

### Update post
PUT http://localhost:8080/posts/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Miwicm9sZSI6InVzZXIiLCJpYXQiOjE3NzM4OTYwODYsImV4cCI6MTc3NDUwMDg4Nn0.Q8ACK98odBjp2-c3yNjsJhHYfKwB1AmzQznPvQvuuFQ

{
  "description": "Updated redis!",
  "category": "testcategory"
}

### Delete post
DELETE http://localhost:8080/posts/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Miwicm9sZSI6InVzZXIiLCJpYXQiOjE3NzM4OTY1OTMsImV4cCI6MTc3NDUwMTM5M30.JAepaJrjIVNVHJEFTPJwMD4cjXafesDw0rTm3Fq5M8k

### Get my posts
GET http://localhost:8080/posts/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Miwicm9sZSI6InVzZXIiLCJpYXQiOjE3NzM4OTY1OTMsImV4cCI6MTc3NDUwMTM5M30.JAepaJrjIVNVHJEFTPJwMD4cjXafesDw0rTm3Fq5M8k

### Get posts by category
GET http://localhost:8080/posts/category/mobility

### GET all of someone's post ex: all posts of userid = 1
GET http://localhost:8080/posts/user/1

### Get postid = 1
GET http://localhost:8080/posts/1

### Generate embedding for post
POST http://localhost:8080/embeddings/generate/4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Miwicm9sZSI6InVzZXIiLCJpYXQiOjE3NzU3MDk5MjgsImV4cCI6MTc3NjMxNDcyOH0.xYDaFyXAtSuTd_mI24wtp3oYYzpuHC4lYw5qmiPAkAw
